INSERT INTO users (name, age) VALUES ('Angelo', 27);
INSERT INTO users (name, age) VALUES ('Jie', 27);
INSERT INTO users (name, age) VALUES ('Lisa', 27);
INSERT INTO users (name, age) VALUES ('Joei', 27);
INSERT INTO users (name, age) VALUES ('Anthony', 27);
INSERT INTO users (name, age) VALUES ('Big', 27);
INSERT INTO users (name, age) VALUES ('Simone', 27);
INSERT INTO users (name, age) VALUES ('Suli', 27);
INSERT INTO users (name, age) VALUES ('Matt', 27);
INSERT INTO users (name, age) VALUES ('Mike', 27);
INSERT INTO users (name, age) VALUES ('Alyssa', 27);
INSERT INTO users (name, age) VALUES ('Aby', 27);
INSERT INTO users (name, age) VALUES ('Angela', 27);
INSERT INTO users (name, age) VALUES ('Ant', 27);
INSERT INTO users (name, age) VALUES ('Bat', 27);
INSERT INTO users (name, age) VALUES ('Cool', 27);
INSERT INTO users (name, age) VALUES ('Tony', 27);
INSERT INTO users (name, age) VALUES ('Rool', 27);
INSERT INTO users (name, age) VALUES ('Tool', 27);
INSERT INTO users (name, age) VALUES ('Shoe', 27);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Bat', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Bottle', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Cat', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Top', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Bop', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Broom', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Hat', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Dog', 'Item', 1000, '3/4/21', '3/12/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Big Barf', 'Item', 1000, '3/4/21', '3/12/21');

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 3);
